language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

env:
    global:
        - TEST_COMMAND="composer test"

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
        - php: 5.6
          env: SYMFONY_VERSION=3.1.*
        - php: 5.6
          env: SYMFONY_VERSION=3.2.*
        - php: 5.6
          env: SYMFONY_VERSION=3.3.*

before_install:
    - travis_retry composer self-update

install:
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
    - $TEST_COMMAND

after_success:
    - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
